---
sudo: false
branches:
  only:
    - travis_test
language: ruby
cache: bundler

before_install:
  - sudo apt-get update
  - sudo apt-get install -y poppler

bundler_args: --without integration --without tools --without development

before_install:
- gem update --system
- gem update bundler
- gem update rake
- gem --version

matrix:
  include:
  - rvm: 2.3
  - rvm: 2.4
  - rvm: 2.5
