name: Release Gem

on:
  release:
    types: [published]

jobs:
  release_gem:
    name: Release to gem hosts
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Rubygems
        uses: cadwallion/publish-rubygems-action@v1.0.0
        with:
          RUBYGEMS_API_KEY: {{ secrets.RUBYGEMS_API_KEY }}
        env:
          RELEASE_COMMAND: rake publish
