name: Push to Master Actions
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Push to Master Actions
    runs-on: ubuntu-latest
    steps:
       - name: Setup ruby
         uses: actions/setup-ruby@v1
       - name: Checkout inspec_tools
         uses: actions/checkout@v2
       - name: Increment version and push tag
         uses: anothrNick/github-tag-action@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
           WITH_V: true
       - name: Install and run github_changelog_generator
         run: |
           gem install github_changelog_generator --no-document
           export CHANGELOG_GITHUB_TOKEN=${{ secrets.PAT }}
           github_changelog_generator -u mitre -p inspec_tools
       - name: Increment Gem Version
         run: printf "module InspecTools\n  VERSION = '$(git describe --tags $(git rev-list --tags --max-count 1) | grep -o "[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+")'.freeze\nend\n" > lib/inspec_tools/version.rb
       - name: Update RELEASE.md
         run: |
           echo "**Release:** " > RELEASE.md
           git describe --tags $(git rev-list --tags --max-count=1) >> RELEASE.md
           echo "<br><br>**Date:** " >> RELEASE.md
           git show -s --format=%ci $(git rev-list --tags --max-count=1) >> RELEASE.md
           echo "<br><br>**Commit:** " >> RELEASE.md
           git rev-list --tags --max-count=1 >> RELEASE.md
       - name: Git Auto Commit
         uses: stefanzweifel/git-auto-commit-action@v4.1.0
         with:
           commit_message: 'Update CHANGELOG.md'
           branch: 'master'
